### PR TITLE
Add install instructions for Fedora

### PR DESCRIPTION
**Pull request by RMPR**
## What kind of change does this PR introduce?
- Other

## Did this PR introduce a breaking change? 
- No

### CODE REVIEW

**Comment by Kethku** [comment]
I don't know much about fedora. Is this the default way to install packages in fedora? Who manages the package?

**Comment by cizordj** [comment]
That seems to be a third-party repository, it is like using a PPA for Ubuntu but in this case it is Fedora-based.

**Comment by RMPR** [comment]
Disclaimer I don't have anything to do with the package owner. It seems it's [chrisbouchard](https://github.com/chrisbouchard), the SRPM is publicly available [here](https://github.com/chrisbouchard/neovide-nightly). I proposed this change because afaik this COPR is the only one on Fedora providing neovide.

**Comment by Kethku** [comment]
I don't think I'm going to merge this as I don't know who posted it or really anything about COPR or Fedora. So adding these instructions would make the repository harder to maintain. Thanks for the pr though!

**Pull request closed without merging**
