### PR TITLE
[Feature] Support Skia Shaders for Cool Effects?

### PR DESCRIPTION
**Pull request by NateAGeek**
This is not meant to be merge, but just a starting spot for the shader feature.

## What kind of change does this PR introduce?
- Feature

## Did this PR introduce a breaking change? 
_A breaking change includes anything that breaks backwards compatibility either at compile or run time._
- Yes, please list breaking changes
- The FPS tanks bc it is compiling a shader on every frame I assume...

### CODE REVIEW

**Comment by Dandelight** [comment]
Very nice, really cool. But do you have a way to turn this effect off? Or adjust this effect. As a passer-by, I'm looking forward to seeing it in the main branch, but I think we should make it configurable before merging.

image

**Comment by A-Lamia** [comment]
It's a shader so you would need to modify the shader file.

**Comment by NateAGeek** [comment]
Yeah, so reviewing on the discord community. I need compile the shader on start, check if platform supports it, add in a configurable system to update uniforms, and also expose a setting to load the shader from a config var. Just need to find the time to hack something together :D

**Comment by Dandelight** [comment]
> Yeah, so reviewing on the discord community. I need compile the shader on start, check if platform supports it, add in a configurable system to update uniforms, and also expose a setting to load the shader from a config var. Just need to find the time to hack something together :D

Lots of work to be done! Feel free to ask the community for help! Many thanks to your innovative idea.

**Comment by Kethku** [comment]
Unfortunately I dont think this is going to get merged. We have two attempts at swapping to wgpu for our rendering and dropping skia altogether. One way or another, our rendering system will change significantly once those merge, so this PR won't work for that.

I'm still working on my attempt at switching to wgpu which is making steady progress (details here: https://kaylees.dev/trio/maple/day16-paths/). If you would like I can try to ping you once that work has landed to get another version of your effects integrated

**Pull request closed without merging**
