### PR TITLE
Release 0.11.0

### PR DESCRIPTION
**Pull request by MultisampledNight**
Just a "formalization" of the 0.11 release, so issues can be linked to it, and we can list what'll be breaking already. ~~I suppose we'll wait with this for some time after #1870 is be merged.~~ Feel free to get involved with testing, feedback and the like!

The list below doesn't list all changes made, but rather what'll be complemented by the autogenerated release notes.

## Breaking

- macOS: `<A-...>` keybindings previously only worked with dead keys. Now it's the other way around, they only work with _non_-dead keys. See https://github.com/neovide/neovide/pull/1899#issuecomment-1622968933. 

## Features

- Config file! https://neovide.dev/config-file.html
- Automatic OS theme change detection, if enabled! https://neovide.dev/configuration.html#theme

## Bug fixes

- Get running on Wayland again!
- IME support!

### CODE REVIEW

**Comment by sisrfeng** [comment]
Look forward to the release! IME support!  (Is there any tweak I can make to get the new IME support before the new release?)

**Comment by MultisampledNight** [comment]
@sisrfeng You can build from source, as covered in https://neovide.dev/installation.html.

**Comment by fredizzimo** [comment]
For this release we should definitely include the deadkey fixes here https://github.com/neovide/neovide/pull/1930 and the fixes for the AppImage here https://github.com/neovide/neovide/pull/1941

And if we can squeeze in the smooth rendering support as well https://github.com/neovide/neovide/pull/1870, it would be great. But that still has some issues on MacOS. But maybe we can document those limitations.
1. The transparency does not work properly on macOS
2. You should run `--novsync` and set `g:neovide_refresh_rate` manually on macOS. Otherwise the frame rate will be unlimited and might consume unnecessary cpu and gpu power.

But we can also wait with that and do another release for the smooth rendering

**Comment by fredizzimo** [comment]
Let's leave the smooth rendering out. That still has some issues to solve.

**Comment by MultisampledNight** [comment]
I believe everything would be ready for the release now, only thing left is actually writing the patch notes and hitting the release button (and maybe a short bitrot period before that in order to squash a few hasty bugs, too).

@fredizzimo would you like to do the release? Or anyone else? I could do it as well, don't have a preference.

**Review by fredizzimo — APPROVED** [review]

**Pull request merged**
