### PR TITLE
cleanup: Remove super verbose logging from font_shaper

### PR DESCRIPTION
**Pull request by last-partizan**
## What kind of change does this PR introduce?
- Other

## Did this PR introduce a breaking change? 
- No

This is really not necessary.

### CODE REVIEW

**Comment by fredizzimo** [comment]
That logging has been useful in a few instances. But I have been worried that someone leaks some sensitive information, since it sends everything that's on the screen, so it's probably good to disable. But the same information is still there for the grid messages, it's just harder to parse. 

I wonder if the best option would be to actually set the logging level, so that these trace messages are not logged by default, but can still be obtained if really needed in order to track down some bug? But that probably means that we have to go through each log message and properly categorize it.

**Comment by last-partizan** [comment]
I was thinking of replacing all `trace` here with `debug`. if it was useful, i'd better do that.

**Comment by fredizzimo** [comment]
I don't think that would help, since trace is supposed to be the most verbose level. It's just that we always log with the trace level enabled at the moment.  https://docs.rs/flexi_logger/latest/flexi_logger/enum.Level.html

**Comment by last-partizan** [comment]
I'm using something like this to trace font shaping:

```
export RUST_LOG="neovide::renderer::fonts::caching_shaper=trace"
```

And if i change it to debug - i will see only relevant messages, and when you need extra tracing - you will see it with trace level.

**Comment by Kethku** [comment]
This seems like a reasonable solution.

**Comment by Kethku** [comment]
@last-partizan feel free to merge as this preserves the useful data in the log file

**Comment by fredizzimo** [comment]
I still don't understand why trace messages are showing in the log and debug ones not, since trace is a lower log level than debug. Since at least in all the other programming languages and logging libraries that I have used it's the other way around, and the documentation that I linked above also seems to indicate that.

Are we specifically turning on the trace log level or something, or is there something I need to learn about the rust logging system, well I know almost nothing about it, so that's probably it.

**Comment by last-partizan** [comment]
@fredizzimo it works as you expect, with level set to `trace` you would see every other messages too, it is most verbose level. With `debug` you would see everithing except `trace`.

**Comment by fredizzimo** [comment]
Yes, but what I mean is that it should correspond to the statements in the code. When I put `trace` in the code, I expect the message to be only shown when trace logging is enabled. Now when it's changed to `debug` I would expect it to show up when either `debug` or `trace` level logging is enabled, so I'm confused how this can make the logging less verbose.

**Comment by last-partizan** [comment]
The main idea is - not to put everything in `trace`, but set level to appropriately for each message.

My main concern when adding this was: i could not see messages about font size, becouse everything was cluttered bug "Shaping text: ...".

Now, when there is different level of verbosity, i just use debug, and can see only those font related messages.

**Comment by fredizzimo** [comment]
Ah sorry, my bad, I must have been too tired yesterday when I looked at the actual changes, since I thought that you changed the shaping messages to debug, but it was the other messages that you changes. So yes, everything makes perfect sense now.

**Pull request merged**
