### PR TITLE
Starting point for a website

### PR DESCRIPTION
**Pull request by cljoly**
- Create a simple Zola website in a subdirectory
- Automate website content update from the README.md and existing graphical assets
- Document how to build and edit the website
- Deploy automatically to GitHub Pages

## What kind of change does this PR introduce?
- Feature (#1089)

## Did this PR introduce a breaking change? 
_A breaking change includes anything that breaks backwards compatibility either at compile or run time._
- No

### CODE REVIEW

**Comment by cljoly** [comment]
See https://cljoly.github.io/neovide/ for a preview.

**Things that need to be done right before merge:**
1. [ ] Make sure that there is a `TOKEN` as described in https://github.com/marketplace/actions/zola-deploy-to-pages#secrets

**Comment by cljoly** [comment]
If we want to have a custom domain, I have neovide.eu.org (free domain managed by an non-profit that nether expires, so low-maintenance), I’m willing to update DNS records as may be needed (and to transfer it, although I’m unsure about the process).

**Comment by Kethku** [comment]
Good point. Another option is I could grab up neovide.dev (or .com) and pay for it with sponsorship money. That way it could be a top level domain.

What do you think?

**Comment by Kethku** [comment]
Can't say enough how awesome this looks btw :) Thanks so much for pushing this forward

**Comment by cljoly** [comment]
> Good point. Another option is I could grab up neovide.dev (or .com) and pay for it with sponsorship money. That way it could be a top level domain.
> 
> What do you think?

As you want. .eu.org is [in](https://publicsuffix.org/list/public_suffix_list.dat) the known [public suffix list](https://publicsuffix.org/), so it should behave like say `.co.uk`. But maybe a .dev is more appealing.

**Comment by cljoly** [comment]
> Can't say enough how awesome this looks btw :)

I've mostly used the defaults of the theme 😉

**Comment by Kethku** [comment]
Maybe I'm just being weird, but I'm not in the EU (or uk) and I know people use neovide from all over, so I'm sorta inclined to get a domain which is location agnostic. Idk if .dev does that or not, but I figure its not a bad way to go

**Comment by cljoly** [comment]
> Maybe I'm just being weird, but I'm not in the EU (or uk) and I know people use neovide from all over, so I'm sorta inclined to get a domain which is location agnostic. Idk if .dev does that or not, but I figure its not a bad way to go

Sure.

**Comment by Kethku** [comment]
Ok I grabbed it up. Its getting late where I'm at, so I'm gonna drop off for now, but this looks good to me :) I see that there is a requirement to add a token. I'll take a look at what that entails soon unless somebody else gets to it sooner.

**Comment by cljoly** [comment]
Awesome, thanks for the review!

**Comment by shaunsingh** [comment]
Looks awesome!

Small nitpick, code blocks for me have a black background but the text itself has a white background. Occurs on macOS 12 on Safari, not sure if other browsers have the issue
image

**Comment by cljoly** [comment]
> Looks awesome!
> 

Thanks!

> Small nitpick, code blocks for me have a black background but the text itself has a white background. Occurs on macOS 12 on Safari, not sure if other browsers have the issue image

Yeah, I agree it’s not ideal, it happens to me as well, both on Android and a desktop Linux with a Chromimum-based browser and Firefox.

It should probably be reported upstream to the theme, as it seems to be caused by this CSS:
image

**Comment by cljoly** [comment]
Shall we set up the token and merge?

I would think the upstream issue [with code text](https://github.com/neovide/neovide/pull/1114#issuecomment-1008282292) is minor enough to be addressed separately.

**Comment by Kethku** [comment]
Done! I will look into what it will take to target the neovide.dev domain to the new website. Thanks again!

**Comment by cljoly** [comment]
I'll send a follow up PR to make Zola generate for neovide.dev (and create the CNAME where GitHub pages expects it.)

**Pull request merged**
