### PR TITLE
Fix shlex::join Deprecation Warning

### PR DESCRIPTION
**Pull request by abhillman**
Addresses https://github.com/neovide/neovide/issues/2313. I'm only beginning to learn Rust, so I'm more than glad to make changes.

## What kind of change does this PR introduce?
- Fix

## Did this PR introduce a breaking change? 
- No

### CODE REVIEW

**Comment by abhillman** [comment]
Here is some additional information regarding `shlex::join`'s deprecation:

* [GitHub Advisory Database: Multiple issues involving quote API in shlex](https://github.com/advisories/GHSA-r7qv-8r2h-pg27)
* Commit from [`comex/rust-shlex`](https://github.com/comex/rust-shlex) that deprecates `shlex::join` https://github.com/comex/rust-shlex/commit/4a0724b0b62ef715467875b040a890ce75a8a829

**Comment by fredizzimo** [comment]
Can you run  `cargo fmt`? After that, I think it should be good to merge.

**Comment by abhillman** [comment]
> Can you run `cargo fmt`? After that, I think it should be good to merge.

We should be good to go.

**Comment by fredizzimo** [comment]
Thank you!

**Pull request merged**
