### PR TITLE
feat: add title bar colours for windows

### PR DESCRIPTION
**Pull request by teehee567**
## What kind of change does this PR introduce?
- Feature

## Did this PR introduce a breaking change? 
- No

### CODE REVIEW

**Comment by fredizzimo** [comment]
Thank you!

Can you rebase onto the latest main? That will fix the Clippy errors. After that you need to run  `cargo fmt`. to fix the formatting errors in the CI.

And before this can be merged the new options need to be documented. 

Finally, you need to apply the settings when the window is created here https://github.com/neovide/neovide/blob/71602b3cde694cd82731c5aa7838bbc182270f50/src/window/window_wrapper.rs#L432, so that they take effect immediately and works anywhere in the nvim configuration.

**Comment by fredizzimo** [comment]
For the documentation can you also add the `**Unrleaased yet.` tag, like this https://github.com/neovide/neovide/blob/281a062949ede46cbc72ba4d6f3cf1390219d0a9/website/docs/configuration.md?plain=1#L335

**Comment by fredizzimo** [comment]
Thanks, I think everything is good now, once the CI failures are fixed.

**Comment by fredizzimo** [comment]
It looks like the rest of the errors are not related to your work. A new rust compiler has been released with new Clippy warnings.

We will fix those errors a bit later, and you can rebase after they are merged.

**Review by falcucci — APPROVED** [review]
took the freedom to rebase your changes @teehee567 

thank you for the contribution!

**Pull request merged**
