### PR TITLE
use firacode nerdfont as default

### PR DESCRIPTION
**Pull request by dineshKumar777**
## What kind of change does this PR introduce?
- Fix
using firacode nerd font instead of regular will resolve one of the most commonly raised issue asking about icons, glyphs are not displayed properly or similar to following
#1430
#1202

this will result in a better default for new comers to our project.

### CODE REVIEW

**Comment by MultisampledNight** [comment]
Thanks, why are you keeping the old Fira Code font then though?

**Comment by LoipesMas** [comment]
Just to be sure: is the font you added licensed under Open Font License (OFL)?

**Comment by dineshKumar777** [comment]
> Thanks, why are you keeping the old Fira Code font then though?

Oops. Will remove it.

>Just to be sure: is the font you added licensed under Open Font License (OFL)?

@LoipesMas  I am not familiar with licensing terms
orginal firacode font is OFL
image

In nerd font case, as per this document its OFL. But pls verify from your end.
https://github.com/ryanoasis/nerd-fonts/blob/master/LICENSE

image

**Comment by LoipesMas** [comment]
Yep, looks like it's OFL.
LGTM then!

**Comment by dineshKumar777** [comment]
@MultisampledNight Deleted regular font. There are other unused files in assets folder. will check with Kethuku before removing those.

**Comment by MultisampledNight** [comment]
Noice, I take that as a "ready to go"?

**Comment by dineshKumar777** [comment]
@MultisampledNight  yes ready. we can merge this

**Comment by kskarthik** [comment]
@dineshKumar777 how can we change the font size of default font now?

**Comment by MultisampledNight** [comment]
Not at all, at the moment. It's hardcoded to be used if no other font is specified, setting `guifont` directly passes that mechanism. Feel free to implement a change which adds the default font to the font discovery mechanism though.

**Comment by kskarthik** [comment]
Just realized, FiraCode is fixed width font anyways :)

**Comment by indyo** [comment]
Is it possible to configure Fira Code variants? I.e "ss01", "ss02", etc

**Comment by MultisampledNight** [comment]
No, it's not (yet). See #1378.

**Pull request merged**
