### PR TITLE
Fall back to key without modifiers

### PR DESCRIPTION
**Pull request by ZyX-II**
## What kind of change does this PR introduce?
- Fix

## Did this PR introduce a breaking change? 

This PR makes it so that more key presses received by neovide will make it to neovim. I am not sure whether this change has effects other than fixing #1646.

### CODE REVIEW

**Comment by ZyX-II** [comment]
Note that this PR relies on Neovim interpreting `<C-6>` same as `<C-^>` (or, for keys I am using, `<C-}>` as `<C-]>`) as Neovide starts feeding it `<C-{whatever key pressed with control}>`. With my customized programmer dvorak layout there is at least one difference between neovide from this PR and nvim-qt: when I type `<C-v><C-!>` I get `<C-!>` in neovide and `^[` in nvim-qt.
With standard US layout there are following differences when pressing `<C-v>{Typed}` (neovide 0.10.3, nvim-qt 0.2.17.0, Windows 10 21H2 build 19044.1526):

Typed     | Neovide  | This PR  | nvim-qt   | Notes
--------- | -------- | -------- | --------- | -----
`<C-~>`   | Ignored  | `^@`     | `^@`      |
`<C-N>`   | Ignored  | `<C-N>`  | `<C-N>`   | For any N, except 6
`<C-6>`   | Ignored  | `^^`     | `^^`      |
`<C-->`   | Ignored  | `<C-->`  | `<C-->`   |
`<C-=>`   | Ignored  | `<C-=>`  | `<C-=>`   |
`<C-BS>`  | `<C-BS>` | `<C-BS>` | `<C-BS>`  |
`<C-S-~>` | Ignored  | `^@`     | `<S-NL>`  |
`<C-S‐1>` | Ignored  | `<C-1>`  | `<C-S-1>` |
`<C-S‐2>` | `^@`     | `^@`     | `<C-S-2>` |
`<C-S‐3>` | Ignored  | `<C-3>`  | `<C-S-3>` |
`<C-S‐4>` | Ignored  | `<C-4>`  | `<C-S-4>` |
`<C-S‐5>` | Ignored  | `<C-5>`  | `<C-S-5>` |
`<C-S‐6>` | `^^`     | `^^`     | `^^`      |
`<C-S‐7>` | Ignored  | `<C-7>`  | `<C-S-7>` |
`<C-S‐8>` | Ignored  | `<C-8>`  | `<C-S-8>` |
`<C-S‐9>` | Ignored  | `<C-9>`  | `<C-S-9>` |
`<C-S‐0>` | Ignored  | Ignored  | Ignored   |
`<C-S-->` | `^_`     | `^_`     | `<C-S-_>` |
`<C-S-=>` | Ignored  | `<C-=>`  | `<C-S-=>` |

**Comment by ZyX-II** [comment]
So solution is far from ideal, nvim-qt works better. I have not yet spotted problems with `<[C-][S-]Fx>` or what I actually type when editing text though.

**Comment by asmodeus812** [comment]
Any chance we get this to work with numbers and ctrl like the issue here suggests - https://github.com/neovide/neovide/issues/1646, for example <C-1> <C-2> etc

**Comment by ZyX-II** [comment]
@asmodeus812 I do not understand the question. This PR is exactly an experiment with fixing #1646, and first comment describes results showing that at least `<C-{number}>` works.

**Comment by fredizzimo** [comment]
#1899 should handle all these cases and some others as well, so this PR is no longer relevant.

**Pull request closed without merging**
