### PR TITLE
fix: Cursor offset

### PR DESCRIPTION
**Pull request by fredizzimo**
## What kind of change does this PR introduce?
* Fixes a regression caused by https://github.com/neovide/neovide/pull/2311. The absolute position of the mouse was returned instead of the relative one.
* A small refactor to the mouse manager, pass a struct instead of individual parameters

* Fixes https://github.com/neovide/neovide/issues/2503

## Did this PR introduce a breaking change? 
- No

### CODE REVIEW

**Comment by 9mm** [comment]
I checked on this branch and it still occurs, but now its only 1 line off instead of 2

**Comment by fredizzimo** [comment]
Hm strange, I just tested all top paddings from 0-20, and all of them work. Maybe this is some macOS specific issue? Maybe affected by the `--frame` parameter?

**Comment by 9mm** [comment]
hmm.. i have spent tons of hours coding today so my mind is tired, but as a quick test i tried...

```
neovide git:(pr/2511) NEOVIDE_FRAME=full NEOVIDE_TITLE_HIDDEN=0 cargo run
```

which i think are the defaults and i got the same effect

these rae the current ones i use

```
export NEOVIDE_FRAME=buttonless
export NEOVIDE_TITLE_HIDDEN=1
export NEOVIDE_VSYNC=0
export NEOVIDE_FORK=1
```

**Comment by 9mm** [comment]
i will eat some food and poke around

**Comment by 9mm** [comment]
I tried a bunch of different options and couldnt seem to make it budge ;/ any ideas of what i should check?

**Comment by 9mm** [comment]
Ah, I have this:

if i comment these out, then it works right:

```
  -- padding
  -- vim.g.neovide_padding_top    = 20
  -- vim.g.neovide_padding_bottom = 20
  -- vim.g.neovide_padding_right  = 20
  -- vim.g.neovide_padding_left   = 20
```

**Comment by fredizzimo** [comment]
Hm.. this PR is supposed to fix the case with the padding. It's broken on main for me and this fixes it.

But I just noticed another bug, the offset gets wrong with splits.

**Comment by fredizzimo** [comment]
Ah, that gave me a clue. If I open a tabbar, then the offset gets wrong in the vertical direction.

**Comment by fredizzimo** [comment]
I went ahead and merged this, since it's a pretty bad regression.

**Pull request merged**
