### PR TITLE
feat: add option to disable window transparency

### PR DESCRIPTION
**Pull request by emonadeo**
Single line change that sets the window transparency based on the user configured transparency, instead of always setting it to true.

(Also removes a redundant `with_transparent` call)

On macOS this slightly changes the window's appearance for opaque backgrounds.

Comparison between Neovide, Kitty and this Pull Request on macOS

(The lack of the borders around the window is something that always has bothered me when using Neovide, because almost all macOS windows have it)

### What kind of change does this PR introduce?
- Feature

### Did this PR introduce a breaking change? 
- No

### CODE REVIEW

**Comment by fredizzimo** [comment]
Thanks,

I think this is a good idea, but I'm not sure that this actually works properly as it's implemented, since `g:neovide_transparency` can be set after the window is created. 

We also need to check how this works on the other platforms.

**Comment by emonadeo** [comment]
Unfortunately setting the transparency after constructing the window [does not work on X11](https://docs.rs/winit/0.29.10/winit/window/struct.Window.html#method.set_transparent) and after testing it myself also doesn't work on macOS. Haven't tested on Windows or Wayland.

I see these options to solve this:

1. Reconstruct the window on every change.
2. Move neovide_transparency to a command line flag. (Breaking change)
   Related: #1891
   (I would even make an argument that all neovide configuration should happen outside of neovim, since having multiple places is confusing imo, but that's a different discussion)
3. Drop this PR (since it probably doesn't matter to most users anyways)

**Comment by falcucci** [comment]
hm I'm not sure if I like it.

I mean, this change just means you want to toggle the transparency.

I would prefer a cmd arg such as `--enable-transparency` and avoid to mix what each setting values aims to be. 

`neovide_transparency` measure the opacity.

window builder settings shouldn't have their values mixed with runtime window settings.

**Comment by emonadeo** [comment]
> hm I'm not sure if I like it.
> 
> 
> 
> I mean, this change just means you want to toggle the transparency.
> 
> 
> 
> I would prefer a cmd arg such as `--enable-transparency` and avoid to mix what each setting values aims to be.
> 
> 
> 
> `g:neovide_transparency` measure the opacity.
> 
> 
> 
> window builder settings shouldn't have their values mixed with runtime window settings. (with no good reason)

An additional cmd arg is a bad idea imho because it adds unnecessary complexity and allows for invalid states (e.g. `--transparent false` and `g:neovide_transparency < 1.0`), when realistically the boolean transparent can be derived from the opacity.

Also there is no clear line between window builder settings and runtime settings because some window settings (like transparent, haven't checked if there are others) are both depending on the OS.

**Comment by falcucci** [comment]
I don't see any complexity, again you just want to toggle transparency and this is what it should do.

Actually the cmd arg should be `--disable-transparency` once all users have it enabled by default. If used, we should just do what it means and that's it, there is no conflict or invalid states.

The only trade-off to decide should be related to `--frame transparent` which must or not be applied to. 

Also, many users update `g:neovide_transparency` during runtime accordingly with back dropped window and necessities.

Rebuilding the window every time it changes isn`t a good option either.

**Comment by emonadeo** [comment]
idk, I am always to add new settings to apps, but I really like the idea of having an inverse option. It's explicit and opt-in so it doesn't affect current users.

Looking at the existing command line options I named it `no-transparency` instead of `disable-transparency`.

It overrides (not overwrites) the `neovide_transparency` vim global and shows a warning whenever the user tries to set `neovide_transparency` to <1.0 while `no-transparency` is set.

**Comment by fredizzimo** [comment]
Sorry for being late about this, but what about calling the setting `--border`? That would be a bit more descriptive and explain what it actually does. 

With the documentation explaining that transparency is not supported. We also need to determine which `--frame` options can be combined with this.

I would like to keep the possibility of supporting transparency with this option by perhaps drawing the border ourselves, or something else, and also support any possible unsupported `--frame` options in combination with this. Maybe at some point make it default and then have a corresponding `--no-border` setting to disable it. Perhaps other platforms could also be supported later.

**Comment by emonadeo** [comment]
I looked into the source code of winit a little bit and it turns out that macOS _does_ support changing transparency after constructing the window, but it looks like this is a bug in winit.

A brief comparison:
[winit/platform_impl/macos/window.rs#494](https://docs.rs/winit/0.29.10/x86_64-apple-darwin/src/winit/platform_impl/macos/window.rs.html#494)
```rust
// set via `with_transparent` when initially constructing the window builder
if attrs.transparent {
    this.setOpaque(false);
    this.setBackgroundColor(&NSColor::clear());
}
```
Compared to when you call `set_transparent` after window construction:
[winit/platform_impl/macos/window.rs#587](https://docs.rs/winit/0.29.10/x86_64-apple-darwin/src/winit/platform_impl/macos/window.rs.html#587)
```rust
pub fn set_transparent(&self, transparent: bool) {
    self.setOpaque(!transparent)
}
```
It looks like it never changes the background color after window construction, so if the window is not initially transparent it defaults to a grey background color (`NSColor::windowBackgroundColor()`), which for some reason is also what causes the border.

Dropping this PR in favor of **TBD**, which achieves the border at runtime and without any command line options.

**Pull request closed without merging**
