### PR TITLE
Fix modifiers behaviour under X11

### PR DESCRIPTION
**Pull request by last-partizan**
## What kind of change does this PR introduce?
- Fix

## Did this PR introduce a breaking change? 
- No

----

This should fix following issues:

- https://github.com/neovide/neovide/issues/951
- https://github.com/neovide/neovide/issues/1142
- https://github.com/neovide/neovide/issues/942

And, i think, most linux keyboard-related issues on x11.
----

Instead of merging new fixes into `new-keyboard-all`, i created `neovide-x11-nt` for both glutin and neovide, based on this: https://github.com/maroider/winit/pull/6

@Kethku if you remember what else was merged into `new-keyboard-all`, i could check if we still need it, and merge into those new branches.

But, it builds, it works, and i've used it without problems for a day.

My main concern here is not to break something on MacOS/Windows.

### CODE REVIEW

**Comment by last-partizan** [comment]
Good we're fixed CI before messing with this :)

For some fucking reason, mac build failed, becouse of missing windows implementation for something :)

**Comment by clason** [comment]
Not Windows, `Window`: Here's my local build failure.
<details>

```
error[E0432]: unresolved imports `crate::event::KeyboardInput`, `crate::event::VirtualKeyCode`
  --> /Users/clason/.cargo/git/checkouts/winit-58efae9df3f5264a/6f91c74/src/platform_impl/macos/event.rs:10:34
   |
10 |     event::{ElementState, Event, KeyboardInput, ModifiersState, VirtualKeyCode, WindowEvent},
   |                                  ^^^^^^^^^^^^^                  ^^^^^^^^^^^^^^ no `VirtualKeyCode` in `event`
   |                                  |
   |                                  no `KeyboardInput` in `event`

error[E0432]: unresolved imports `crate::event::KeyboardInput`, `crate::event::VirtualKeyCode`
  --> /Users/clason/.cargo/git/checkouts/winit-58efae9df3f5264a/6f91c74/src/platform_impl/macos/view.rs:22:43
   |
22 |         DeviceEvent, ElementState, Event, KeyboardInput, ModifiersState, MouseButton,
   |                                           ^^^^^^^^^^^^^ no `KeyboardInput` in `event`
23 |         MouseScrollDelta, TouchPhase, VirtualKeyCode, WindowEvent,
   |                                       ^^^^^^^^^^^^^^ no `VirtualKeyCode` in `event`

error[E0412]: cannot find type `KeyEventExtra` in module `platform_impl`
   --> /Users/clason/.cargo/git/checkouts/winit-58efae9df3f5264a/6f91c74/src/event.rs:677:50
    |
677 |     pub(crate) platform_specific: platform_impl::KeyEventExtra,
    |                                                  ^^^^^^^^^^^^^ not found in `platform_impl`

error[E0603]: struct import `ModifiersState` is private
   --> /Users/clason/.cargo/git/checkouts/winit-58efae9df3f5264a/6f91c74/src/platform_impl/macos/event.rs:10:49
    |
10  |     event::{ElementState, Event, KeyboardInput, ModifiersState, VirtualKeyCode, WindowEvent},
    |                                                 ^^^^^^^^^^^^^^ private struct import
    |
note: the struct import `ModifiersState` is defined here...
   --> /Users/clason/.cargo/git/checkouts/winit-58efae9df3f5264a/6f91c74/src/event.rs:41:22
    |
41  |     keyboard::{self, ModifiersState},
    |                      ^^^^^^^^^^^^^^
note: ...and refers to the struct `ModifiersState` which is defined here
   --> /Users/clason/.cargo/git/checkouts/winit-58efae9df3f5264a/6f91c74/src/keyboard.rs:93:1
    |
93  | / bitflags! {
94  | |     /// Represents the current state of the keyboard modifiers
95  | |     ///
96  | |     /// Each flag represents a modifier and is set if this modifier is active.
...   |
117 | |     }
118 | | }
    | |_^ consider importing it directly
    = note: this error originates in the macro `bitflags` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0603]: struct import `ModifiersState` is private
   --> /Users/clason/.cargo/git/checkouts/winit-58efae9df3f5264a/6f91c74/src/platform_impl/macos/view.rs:22:58
    |
22  |         DeviceEvent, ElementState, Event, KeyboardInput, ModifiersState, MouseButton,
    |                                                          ^^^^^^^^^^^^^^ private struct import
    |
note: the struct import `ModifiersState` is defined here...
   --> /Users/clason/.cargo/git/checkouts/winit-58efae9df3f5264a/6f91c74/src/event.rs:41:22
    |
41  |     keyboard::{self, ModifiersState},
    |                      ^^^^^^^^^^^^^^
note: ...and refers to the struct `ModifiersState` which is defined here
   --> /Users/clason/.cargo/git/checkouts/winit-58efae9df3f5264a/6f91c74/src/keyboard.rs:93:1
    |
93  | / bitflags! {
94  | |     /// Represents the current state of the keyboard modifiers
95  | |     ///
96  | |     /// Each flag represents a modifier and is set if this modifier is active.
...   |
117 | |     }
118 | | }
    | |_^ consider importing it directly
    = note: this error originates in the macro `bitflags` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0603]: struct import `ModifiersState` is private
   --> /Users/clason/.cargo/git/checkouts/winit-58efae9df3f5264a/6f91c74/src/platform_impl/macos/window_delegate.rs:19:20
    |
19  |     event::{Event, ModifiersState, WindowEvent},
    |                    ^^^^^^^^^^^^^^ private struct import
    |
note: the struct import `ModifiersState` is defined here...
   --> /Users/clason/.cargo/git/checkouts/winit-58efae9df3f5264a/6f91c74/src/event.rs:41:22
    |
41  |     keyboard::{self, ModifiersState},
    |                      ^^^^^^^^^^^^^^
note: ...and refers to the struct `ModifiersState` which is defined here
   --> /Users/clason/.cargo/git/checkouts/winit-58efae9df3f5264a/6f91c74/src/keyboard.rs:93:1
    |
93  | / bitflags! {
94  | |     /// Represents the current state of the keyboard modifiers
95  | |     ///
96  | |     /// Each flag represents a modifier and is set if this modifier is active.
...   |
117 | |     }
118 | | }
    | |_^ consider importing it directly
    = note: this error originates in the macro `bitflags` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0559]: variant `event::WindowEvent<'_>::KeyboardInput` has no field named `input`
   --> /Users/clason/.cargo/git/checkouts/winit-58efae9df3f5264a/6f91c74/src/platform_impl/macos/event.rs:293:13
    |
293 |             input: KeyboardInput {
    |             ^^^^^ `event::WindowEvent<'_>::KeyboardInput` does not have this field
    |
    = note: available fields are: `device_id`, `event`, `is_synthetic`

error[E0283]: type annotations needed
  --> /Users/clason/.cargo/git/checkouts/winit-58efae9df3f5264a/6f91c74/src/platform_impl/macos/view.rs:78:20
   |
78 |         modifiers: Default::default(),
   |                    ^^^^^^^^^^^^^^^^ cannot infer type
   |
   = note: cannot satisfy `_: std::default::Default`

error[E0599]: no variant or associated item named `ReceivedCharacter` found for enum `event::WindowEvent` in the current scope
   --> /Users/clason/.cargo/git/checkouts/winit-58efae9df3f5264a/6f91c74/src/platform_impl/macos/view.rs:528:37
    |
528 |                 event: WindowEvent::ReceivedCharacter(character),
    |                                     ^^^^^^^^^^^^^^^^^ variant or associated item not found in `event::WindowEvent<'_>`
    |
   ::: /Users/clason/.cargo/git/checkouts/winit-58efae9df3f5264a/6f91c74/src/event.rs:212:1
    |
212 | pub enum WindowEvent<'a> {
    | ------------------------ variant or associated item `ReceivedCharacter` not found here

error[E0599]: no variant or associated item named `ReceivedCharacter` found for enum `event::WindowEvent` in the current scope
   --> /Users/clason/.cargo/git/checkouts/winit-58efae9df3f5264a/6f91c74/src/platform_impl/macos/view.rs:552:37
    |
552 |                 event: WindowEvent::ReceivedCharacter('\r'),
    |                                     ^^^^^^^^^^^^^^^^^ variant or associated item not found in `event::WindowEvent<'_>`
    |
   ::: /Users/clason/.cargo/git/checkouts/winit-58efae9df3f5264a/6f91c74/src/event.rs:212:1
    |
212 | pub enum WindowEvent<'a> {
    | ------------------------ variant or associated item `ReceivedCharacter` not found here

error[E0599]: no variant or associated item named `ReceivedCharacter` found for enum `event::WindowEvent` in the current scope
   --> /Users/clason/.cargo/git/checkouts/winit-58efae9df3f5264a/6f91c74/src/platform_impl/macos/view.rs:563:45
    |
563 |                         event: WindowEvent::ReceivedCharacter(character),
    |                                             ^^^^^^^^^^^^^^^^^ variant or associated item not found in `event::WindowEvent<'_>`
    |
   ::: /Users/clason/.cargo/git/checkouts/winit-58efae9df3f5264a/6f91c74/src/event.rs:212:1
    |
212 | pub enum WindowEvent<'a> {
    | ------------------------ variant or associated item `ReceivedCharacter` not found here

error[E0559]: variant `event::WindowEvent<'_>::KeyboardInput` has no field named `input`
   --> /Users/clason/.cargo/git/checkouts/winit-58efae9df3f5264a/6f91c74/src/platform_impl/macos/view.rs:665:17
    |
665 |                 input: KeyboardInput {
    |                 ^^^^^ `event::WindowEvent<'_>::KeyboardInput` does not have this field
    |
    = note: available fields are: `device_id`, `event`, `is_synthetic`

error[E0599]: no variant or associated item named `ReceivedCharacter` found for enum `event::WindowEvent` in the current scope
   --> /Users/clason/.cargo/git/checkouts/winit-58efae9df3f5264a/6f91c74/src/platform_impl/macos/view.rs:682:45
    |
682 |                         event: WindowEvent::ReceivedCharacter(character),
    |                                             ^^^^^^^^^^^^^^^^^ variant or associated item not found in `event::WindowEvent<'_>`
    |
   ::: /Users/clason/.cargo/git/checkouts/winit-58efae9df3f5264a/6f91c74/src/event.rs:212:1
    |
212 | pub enum WindowEvent<'a> {
    | ------------------------ variant or associated item `ReceivedCharacter` not found here

error[E0559]: variant `event::WindowEvent<'_>::KeyboardInput` has no field named `input`
   --> /Users/clason/.cargo/git/checkouts/winit-58efae9df3f5264a/6f91c74/src/platform_impl/macos/view.rs:720:17
    |
720 |                 input: KeyboardInput {
    |                 ^^^^^ `event::WindowEvent<'_>::KeyboardInput` does not have this field
    |
    = note: available fields are: `device_id`, `event`, `is_synthetic`

error[E0559]: variant `event::WindowEvent<'_>::KeyboardInput` has no field named `input`
   --> /Users/clason/.cargo/git/checkouts/winit-58efae9df3f5264a/6f91c74/src/platform_impl/macos/view.rs:839:17
    |
839 |                 input: KeyboardInput {
    |                 ^^^^^ `event::WindowEvent<'_>::KeyboardInput` does not have this field
    |
    = note: available fields are: `device_id`, `event`, `is_synthetic`

error[E0599]: no method named `reset_dead_keys` found for struct `platform_impl::platform::Window` in the current scope
   --> /Users/clason/.cargo/git/checkouts/winit-58efae9df3f5264a/6f91c74/src/window.rs:460:21
    |
460 |         self.window.reset_dead_keys();
    |                     ^^^^^^^^^^^^^^^ method not found in `platform_impl::platform::Window`
    |
   ::: /Users/clason/.cargo/git/checkouts/winit-58efae9df3f5264a/6f91c74/src/platform_impl/macos/mod.rs:43:1
    |
43  | pub struct Window {
    | ----------------- method `reset_dead_keys` not found for this
```
</details>

**Comment by Kethku** [comment]
Yeah this winit branch doesn't have all the keyboard branches merged in yet which is why we haven't swapped to using the new one. @last-partizan we're pretty stalled on this I think unless we should create a new all-keyboard branch. I'll go offer to build such a thing in the main repository and see how that lands.

**Comment by Kethku** [comment]
https://github.com/rust-windowing/winit/pull/2143#issuecomment-1028580212

I asked here. Hopefully it doesn't come across as pushy, but I think given the interest, we might be able to contribute and push the keyboard work along which would help the whole ecosystem. We'll see what they say

**Comment by korsmakolnikov** [comment]
Could that be my issue? 
After executing neovide dead keys stop working. Running ibus-setup and uncheck/check "use system keyboard layout" something is resetting and dead keys start to work again. 

I'm switching down to nvim by now. I hope to try this fix soon.

**Comment by mutlusun** [comment]
Thanks for this pull request. I have tested it locally and it fixed for me #1142 .

**Comment by tobealive** [comment]
What needs to be done on this to be merged, and how can we help 😊?

**Comment by last-partizan** [comment]
@tobealive if you're on linux, you can use this branch temporarily.

In the long run we're waiting for this: https://github.com/rust-windowing/winit/pull/2143#issuecomment-1028580212

**Comment by tobealive** [comment]
> @tobealive if you're on linux, you can use this branch temporarily.
> 
> In the long run we're waiting for this: [rust-windowing/winit#2143 (comment)](https://github.com/rust-windowing/winit/pull/2143#issuecomment-1028580212)

Hello nice to read your reply! Yes, using the fork for now. Thanks for the link, I didn't get that context. Look like it's really patience that's the key here.

**Comment by tobealive** [comment]
It looks like all the necessary merges happened around a month ago. Therefore - audacious as I am - I would ask how it looks with a merge. 😇

**Comment by MultisampledNight** [comment]
According to the CI building on Mac fails, so merging right now is not a good idea.

**Comment by last-partizan** [comment]
I tried building this with `winit:new-keyboard`, and it failed, becouse of errors in that branch.

```
winit > cargo test
...
error: could not compile `winit` due to 22 previous errors
```

We should try again in a few months :)

**Comment by MultisampledNight** [comment]
Recent activity in the Matrix/IRC channel of winit also shows that having one single branch on upstream we can depend on isn't that far away. But they can take their time.

**Comment by fecet** [comment]
I can't open it after install this branch

**Comment by HadziqM** [comment]
i cant open the binary after build too

##Device Information
Operating System: Linux Mint 21.1                 
Kernel: Linux 5.15.0-56-generic
Architecture: x86-64

Nvim: version 0.8.0

##log file
[neovide_rCURRENT.log](https://github.com/neovide/neovide/files/10312325/neovide_rCURRENT.log)

**Comment by last-partizan** [comment]
Closing this PR in favor of #1789.

**Pull request closed without merging**
