### PR TITLE
Push Event `ModifiersChanged` to `queued_input_events`

### PR DESCRIPTION
**Pull request by quadruple-output**
The input event `ModifiersChanged` has to be processed in the correct
order together with `KeyEvent` and `ImeInput`. Otherwise, glitches can
occur, resulting in modifiers being ignored.

## What kind of change does this PR introduce?
Fixes neovide/neovide#1358

## Did this PR introduce a breaking change? 
_A breaking change includes anything that breaks backwards compatibility either at compile or run time._
No

### CODE REVIEW

**Comment by MultisampledNight** [comment]
I can't test the specific case in the linked issue, as I don't have a programmable keyboard, but if it improves the situation for you, great.

Though this change seems to break input after re-focus on Wayland.

Also, please consider changing the branch name from `main` _in future_, this allows checking out only your PR branch through `git fetch origin pull/1359/head:whatever-branch-name` and not every single other branch that still exist (by adding an entire new remote).

**Comment by quadruple-output** [comment]
Thanks a lot for your feedback, @MultisampledNight .

> Though this change seems to break input after re-focus on Wayland.

I have a linux laptop running wayland (though I rarely use it), and I would like to test this. I just need to be clear on how to reproduce the broken input. (Playing around a bit, changing focus by keyboard and mouse, I could not recognize any issue. Running arch linux, all packages up-to-date.)
1) What does "break input" mean exactly?
2) Does it matter _how_ I achieve the re-focus? Should I enable focus-follows-mouse, or rather change focus with the keyboard?

Sorry for re-using the `main` branch. I will be happy to open a _new_ PR if that makes sense (in case I manage to fix the "broken input" issue).

**Comment by MultisampledNight** [comment]
Sorry, I'll be more specific: I'm using Sway 1.7 stable. As long as the window focused the first time, input works perfectly. But once Neovide loses focus in any way, may it just be due to workspace switching, no input at all seems to get through to Neovim. Not even `:` works, but closing the window does.

Sway uses a focus-follow-mouse model, for me it's reproduceable every time. I don't know if that's reproduceable with other window managers.

The branch name is fine, no worries. Just for the next time.

**Comment by last-partizan** [comment]
@quadruple-output try to test branch `fix-stuck-shift`, does that fixes issues for you?

**Comment by quadruple-output** [comment]
> @quadruple-output try to test branch `fix-stuck-shift`, does that fixes issues for you?

Unfortunately not. I have to say it generally got better, meaning that the issue occurs much less frequently. I can type `}` ~100 times or more now, before the issue occurs once. I see this improvement also for the main branch, but I have no clue where the difference could come from. Could be due to improvements in neovide or just a MacOS update.

**Comment by fredizzimo** [comment]
This is no longer relevant with #1899. No events are queued anymore.

**Pull request closed without merging**
