### PR TITLE
Touch support (scrolling, click-by-tap, visual selection by dragging)

### PR DESCRIPTION
**Pull request by MultisampledNight**
## What kind of change does this PR introduce?
- Feature
  - Touch scrolling
  - Clicking by touch tapping
  - Creating a visual selection through touch dragging (hold down finger for a bit and move)

## Did this PR introduce a breaking change? 
_A breaking change includes anything that breaks backwards compatibility either at compile or run time._
- Yes, please list breaking changes
  - Touch input is actually handled now instead of ignored

This PR introduces general touch support (despite the branch name). From what I understood this has been supported in the past already, but was broken by a move to `sdl2` _and back to `winit`?_

While the new setting values (namely `touch_deadzone` and `touch_drag_timeout`) are undocumented yet, I'd be happy to do that in the `Wiki` tab, but I can't seem to edit there. It should probably belong to the `Input Settings` section though.

### CODE REVIEW

**Comment by TornaxO7** [comment]
It works for me. Tested on the acer spin 5.

**Comment by MultisampledNight** [comment]
Since this is my own PR, I would rather not like to merge it myself. So in case someone with merge permissions stumbles across this, I'd be happy if you'd review a bit and then merge.

**Review by fredizzimo — APPROVED** [review]
I didn't see any problems. But I'll leave this open a bit still, in case someone else wants to review. And I have also not tested the code. I don't see how it could break normal mouse behaviour, but there's always the possibility.

Finally I'm not sure if we want to have a feature freeze before the release or not.

**Comment by Kethku** [comment]
I don't have a strong opinion either way. Regardless, I think we should move to more frequent releases after this one so shouldn't be a big deal if we wait

**Comment by shaunsingh** [comment]
The PR likely won't create any new issues, and I imagine its a feature atleast a few people would like. Code LGTM as well, I don't have any issues with merging it before the next release.

**Comment by Kethku** [comment]
I agree.

**Comment by MultisampledNight** [comment]
Nice, I'll document it. Thanks for your time!

**Pull request merged**
