### PR TITLE
feat: implement dynamic window title visibility option

### PR DESCRIPTION
**Pull request by falcucci**
PR needed to complement #2168 

## What kind of change does this PR introduce?
- Feature

## Did this PR introduce a breaking change? 
_A breaking change includes anything that breaks backwards compatibility either at compile or run time._
- No

### CODE REVIEW

**Comment by fredizzimo** [comment]
I think, I would rather see that we fix https://github.com/neovide/neovide/pull/2126, to allow an empty titestring if set explicitly. `Neovide` would still remain the default if unset 

This way it works on all platforms, and we don't need any custom options

**Comment by falcucci** [comment]
@fredizzimo got it working.

notice that:

- IF `title` is enabled and `titlestring` is empty, neovim sends `[No Name] - NVIM` as value;
- IF `title` is 0 then it is really empty as expeted;

**Comment by fredizzimo** [comment]
Hm.. Yes, it does not seem to work the way I imagined. 

I guess we need an option to hide the title then, I don't think we should modify the default one. The option could just force it to empty, since that should be crossplatform

**Comment by falcucci** [comment]
@fredizzimo done, work just fine. If you want to release you can use this to complement #2168 

I'll be idle for now, come back tomorrow

**Comment by fredizzimo** [comment]
I rebased and fixed a warning from https://github.com/neovide/neovide/pull/2168 on non-macos platforms

**Pull request merged**
