### PR TITLE
Run WSL Neovim inside a login shell

### PR DESCRIPTION
**Pull request by fredizzimo**
Currently WSL is launched with a hack to launch a temporary interactive shell in order to fix the path inside Neovim, but it leaves all other environment variables unset, and does not correctly load all your login scripts.  See this flowchart from https://shreevatsa.wordpress.com/2008/03/30/zshbash-startup-files-loading-order-bashrc-zshrc-etc/

flowchart

This  pull request changes that, so that Neovim is launched inside an interactive shell, and all settings and scripts are read correctly, at least I haven't seen any problems on my system. 

I also refactored the command line processing to unify the code paths taken on different systems and to avoid duplicating the code.

Note that there's a tiny problem, it does not necessarily work if you spawn another shell from within your bash scripts, like the Genie instructions here for example suggests https://github.com/arkane-systems/genie/wiki/Automatically-start-genie-on-every-shell-session. I had that problem when using Zsh as the default shell, but not when using Bash. I'm not sure if that problem can be solved at all, but I got rid of the problem by switching to https://github.com/nullpo-head/wsl-distrod, which is superior to Genie in many other ways too IMO.

My suggested fix for this is to document this, and instruct the users to fix their shell scripts to not start any subshells, another option is to add some command line parameter to choose between interactive and login shell.

Fixes https://github.com/neovide/neovide/issues/950
Fixes https://github.com/neovide/neovide/issues/983

### CODE REVIEW

**Comment by Lite5h4dow** [comment]
looks good. thanks for this.

**Comment by fredizzimo** [comment]
Have anyone been able to test this yet, does it work for you? Do you think it's a good default behaviour, and do we need to add some flags to revert back to the old behaviour?

**Comment by Kethku** [comment]
This looks good to me imho. My wsl instance is pretty borked atm (I think I accidentally deleted some of the files trying to free up space). But the refactoring to simplify creation of the neovim process is worth it in and of itself. @fredizzimo feel free to merge w/e you feel its ready

**Comment by fredizzimo** [comment]
I will merge this now, since I think that's the best way of getting actual feedback. I have been using it myself for over a month without problems on a couple of different machines. But obviously that's not a big sample. 

If people do get problems, a likely cause is the one that I described above. Some init script that spawns an inner shell. This needs to at least be documented some way, But I think the discussion of exactly how, and what can be done about it can be discussed in some issue. 

Also some sort of error handling needs to be done, since right now it just hangs if the nvim process can be launched, but the communication fails, but that's a general problem and should be handled on all platforms.

**Comment by HUAHUAI23** [comment]
hi I'm starting neovide via neovide --wsl, how do I source .bashrc to set some environment variables when I start neovide?

**Pull request merged**
