### PR TITLE
Don't re-open files already present in args

### PR DESCRIPTION
**Pull request by singiamtel**
Fixes https://github.com/neovide/neovide/issues/2609.

My fix is quite ugly, I understand if this is not the path the maintainers want to take to fix this. I'm happy to implement better suggestions, I just want the bug gone

I think the regression was in fcf5e87b 

## What kind of change does this PR introduce?
- Fix

## Did this PR introduce a breaking change? 
- No

### CODE REVIEW

**Comment by fredizzimo** [comment]
Thank you!

This solves part of the problem. But there's another related problem:
* https://github.com/neovide/neovide/issues/2629

It would be nice if we could delay the launch of Neovim until all the initial `handle_open_files` have been called, then merge the `neovim_args` and send the whole list as arguments to Neovim. If I recall correctly, there's another event that is sent, when all the initial `handle_open_files` have been handled. 

But note that this should only be done for the initial launch, `handle_open_files` should still be sent as `FileDrop` after Neovim has been launched.

Since, this is quite complex, I understand if you can't or don't want to implement this. But I would rather merge the complete solution, than a workaround which will have to be replaced later.

**Comment by fredizzimo** [comment]
@falcucci, could you test this at some point? Since I can't do it myself.

**Comment by singiamtel** [comment]
Hi @fredizzimo,

I've been trying to understand the events better but haven't made much progress. I think the bug is a race condition, adding this print is enough to break the repro in my local machine...

```diff
diff --git a/src/window/mod.rs b/src/window/mod.rs
index 663d5d3..13932a7 100644
--- a/src/window/mod.rs
+++ b/src/window/mod.rs
@@ -290,6 +290,7 @@ pub fn main_loop(
     let res = event_loop.run(move |e, window_target| {
         #[cfg(target_os = "macos")]
         menu.ensure_menu_added(&e);
+        println!("{:?}", e);
 
         match e {
             Event::Resumed => {
```

So the proper fix is probably too much for me, specially as this is my first time working on this codebase. 

I'll fix the format error on the CI, feel free to either merge the workaround or close the PR

**Comment by fredizzimo** [comment]
I think this can be closed, we merged this
* https://github.com/neovide/neovide/pull/2798

**Pull request closed without merging**
