### PR TITLE
fix: C-Space was not mappable on Windows

### PR DESCRIPTION
**Pull request by Geobert**
Fixes https://github.com/neovide/neovide/issues/2669

## What kind of change does this PR introduce?
- Fix

## Did this PR introduce a breaking change? 
- No

I had this keymap that wasn’t working before the change and works with it
```
vim.keymap.set('n', '<C-Space>', '<cmd>echomsg "Test!"<CR>')
```

### CODE REVIEW

**Comment by Geobert** [comment]
Not sure what happend here, but I think my change has nothing to do with it 😅

**Comment by fredizzimo** [comment]
Yes, the Window CI builds have been broken for a while, and I think we won't merge that until it's fixed. I made a comment here https://github.com/neovide/neovide/pull/2641#issuecomment-2156021707, but since I'm on vaccation, I haven't been able to do anything about it myself.

There is a problem with your code though, if you check the files tab, `cargo clippy` does not like the `== None` check. That's also the other reason I want to get rid of reviewdog, the output is confusing and the errors hard to spot.

**Comment by Geobert** [comment]
Sorry about that :)

**Comment by fredizzimo** [comment]
The CI has finally been fixed now, can you rebase on top of main?

**Comment by fredizzimo** [comment]
Thank you!

**Pull request merged**
