### PR TITLE
Extra context if can't save to file

### PR DESCRIPTION
**Pull request by dev-ardi**
## What kind of change does this PR introduce?
- Fix

## Did this PR introduce a breaking change? 
- No

Gives more context for errors such as #2132 so that the user can fix them.

### CODE REVIEW

**Review by fredizzimo — CHANGES_REQUESTED** [review]
Can you format the code with `cargo fmt`?

There are also a couple of clippy errors, see the "files changed" tab for the output, or run `cargo clippy` locally.

**Comment by dev-ardi** [comment]
I should have checked before, my bad

**Comment by dev-ardi** [comment]
No idea why it was failing on those files, I didn't change them

**Comment by fredizzimo** [comment]
Thanks you!

> No idea why it was failing on those files, I didn't change them

Each new version of clippy adds a few more checks, and there's no way to lock to a specific version, the newest version is always used. So unfortunately that's expected.

**Comment by dev-ardi** [comment]
I meant fmt was failing! maybe someone commited directly to master without passing through CI?

**Comment by fredizzimo** [comment]
Your `cargo clippy --fix` commit actually touched those files. 

Rust 1.74 was released the 16th November, so that's why you started to see new clippy warnings.

**Pull request merged**
