### PR TITLE
feat: support all font weights and slants

### PR DESCRIPTION
**Pull request by TwIStOy**
## What kind of change does this PR introduce?
- Feature

## Did this PR introduce a breaking change? 
_A breaking change includes anything that breaks backwards compatibility either at compile or run time._
- No

### CODE REVIEW

**Comment by fredizzimo** [comment]
Thank You!

Do you think it would be possible to also support numerical values, perhaps `Weight400`, for the same as normal for example? At least weight supports it, and perhaps slant as well.

This was already attempted here, but stalled due to not having a good way of configuring it
* https://github.com/neovide/neovide/pull/2121

**Comment by TwIStOy** [comment]
Make variable font weight can be set in font's style now!

**Comment by fredizzimo** [comment]
Great! I think this is good once some documentation is added with the supported options.

**Review by fredizzimo — APPROVED** [review]
Thank you, this looks good to me. But I'm leaving it open for a while before merging, to allow other people to review.

**Review by falcucci — APPROVED** [review]

**Comment by Kethku** [comment]
Thanks for the change! Works great

**Pull request merged**
