### PR TITLE
add neovide_input_use_logo to toggle logo handling

### PR DESCRIPTION
**Pull request by lucas-miranda**
it also completely ignores keyboard inputs with D modifier

As already discussed at #763, it introduces `g:neovide_input_use_logo` to toggle between logo input handling or ignoring inputs using this modifier and, because of that, it's a feature to normalize usage with terminals (to what people are used to).

So isn't our problem anymore `<D->` been typed, if that option is active, because it works as any function key when using at insert mode.

I'm sure it can close both #763 and #826

About the code itself, if I've made any mistake about organization or something like that, please let me know
I can include documentation at wiki about the option too

## What kind of change does this PR introduce?
- [ ] Fix
- [X] Feature
- [ ] Codestyle
- [ ] Refactor
- [ ] Other

## Did this PR introduce a breaking change?
_A breaking change includes anything that breaks backwards compatibility either at compile or run time._
- [ ] Yes, please list breaking changes
- [X] No

### CODE REVIEW

**Comment by Kethku** [comment]
This looks pretty sweet to me! I've sent you an invite to the project. If you're willing to add docs to the wiki for the new setting, that would be awesome. Otherwise I'll get to it eventually. Thanks so much for the fix!

**Comment by Kethku** [comment]
Actually before I merge, could you fix the formatting? The lint build failed.

**Comment by lucas-miranda** [comment]
I've fixed the lint errors and I already added a [Input Settings](https://github.com/neovide/neovide/wiki/Configuration#input-settings) section and [Use Logo Key](https://github.com/neovide/neovide/wiki/Configuration#use-logo-key) sub-section to the wiki

**Comment by Kethku** [comment]
Thanks again!

**Pull request merged**
