### PR TITLE
feat: rename and deprecate `neovide_transparency` to `neovide_opacity`

### LINKED ISSUE #2701: feature: rename and deprecate `neovide_transparency` to `neovide_opacity`

### PR DESCRIPTION
**Pull request by lucobellic**
Rename `neovide_transparency` to `neovide_opacity`. 
Changes to `neovide_transparency` will update `WindowSettings::opacity`. 

- Update all documentation and references to use `neovide_opacity`. 
- Rename `WindowSettings` transparency to opacity for consistency. 
- Add `alias` attribute to the `SettingGroup` macro.
- ~Update the test `test_read_initial_values` with alias.~
  Test removed since aliases are excluded from `read_initial_values` to not trigger deprecation message at startup.
- Add deprecation message for settings with alias attribute. 
  `Error: neovide_transparency has now been deprecated, use neovide_opacity instead.`
                                                                                                                        
~I don't know if a deprecation message is needed and how to properly handle `neovide_transparency` deprecation, let me know.~

## What kind of change does this PR introduce?
- Feature

## Did this PR introduce a breaking change? 
- No

Feel free to edit or request any changes

Close  #2701

### CODE REVIEW

**Comment by fredizzimo** [comment]
For the deprecation warning, you can model it after this:
https://github.com/neovide/neovide/blob/000b75c0f3bcfb602967cc5c2e8a9d584be06a02/src/window/macos.rs#L180C12-L180C39

**Comment by fredizzimo** [comment]
The macOS build failure is not your fault. Something has changed in the nightly compiler. This might fix it, but I'm not sure:
* https://github.com/neovide/neovide/pull/2768

**Comment by lucobellic** [comment]
Code updated with deprecation message.
I just had to exclude `transparency` key from `read_initial_values` to avoid triggering the deprecation message at startup.

**Comment by Kethku** [comment]
Merging into transparency

**Pull request merged**
