### PR TITLE
wip: move skia renderer into renderer/

### PR DESCRIPTION
**Pull request by last-partizan**
This is start for refactoring Renderer.

I started by moving SkiaRenderer from GlutinWindowWrapper into Renderer.

@Kethku please, take a look. After this refactoring i'm getting error, any suggestions on how to deal with it?

```
error[E0499]: cannot borrow `*self` as mutable more than once at a time
   --> src/renderer/mod.rs:107:13
    |
101 |         let root_canvas = self.skia_renderer.canvas();
    |                           ------------------ first mutable borrow occurs here
...
107 |             self.handle_draw_command(root_canvas, draw_command);
    |             ^^^^                     ----------- first borrow later used here
    |             |
    |             second mutable borrow occurs here
```

## What kind of change does this PR introduce?
- Refactor

## Did this PR introduce a breaking change? 
- No

### CODE REVIEW

**Comment by last-partizan** [comment]
Whoa, turns out when i refactored other parts this issue just disappeared. Probabply i'm going in right direction :)

**Comment by last-partizan** [comment]
No, it didn't disappeared. I just got obscured by other errors.

**Comment by last-partizan** [comment]
I moved skia_renderer back into GlutinWindowWrapper, now it compiles, but it still looks ugly and has some bugs.

**Comment by last-partizan** [comment]
I'm abandoning this refactoring for now, as it was not clearly better, just another sort of spaghetti.

**Comment by Kethku** [comment]
Apologies for not pitching in to review/take a look at this :( I've been busy with other projects for a bit

**Pull request closed without merging**
