### PR TITLE
fix(cargo.toml): rm debug symbols in release build

### PR DESCRIPTION
**Pull request by kskarthik**
Helps further slimming of the binary. 

Info:
1. https://doc.rust-lang.org/cargo/reference/profiles.html#strip
2. https://github.com/johnthagen/min-sized-rust#optimize-for-size

## What kind of change does this PR introduce?
- Feature

## Did this PR introduce a breaking change? 
- No

### CODE REVIEW

**Review by last-partizan — APPROVED** [review]
Looks good to me

**Comment by LoipesMas** [comment]
I think we'd rather optimize for speed, not size. 
And from my testing it looks like the difference is negligible anyway:
image
That's current profile, with `strip = true` added and with `strip = true` and `opt-level = "z"` added, respectively.
It's a 4mb difference at most, so I'm not sure if potential performance loss is worth it.
Maybe if we did a benchmark and there were no performance loss.

**Comment by kskarthik** [comment]
@LoipesMas so `strip=true` should be good to go, if performace is the choice

**Comment by LoipesMas** [comment]
Yeah, just stripping should be fine.

**Pull request merged**
