### PR TITLE
error: there is no argument named `min_ft` solved

### PR DESCRIPTION
**Pull request by huncut2016**
## What kind of change does this PR introduce?
- Fix (I can't compile on my computer, and this small code change fixed it)

## Did this PR introduce a breaking change? 
_A breaking change includes anything that breaks backwards compatibility either at compile or run time._
- No

### CODE REVIEW

**Comment by MultisampledNight** [comment]
By the way, the change is not needed if you run `rustup update`. Since Rust 1.58, which was released on January 22th, Rust can capture variables in such format strings directly.

**Review by j4qfrost — APPROVED** [review]
LGTM

**Comment by LoipesMas** [comment]
As MultisampledNight said, it's a fairly new rust feature, so updating your rust toolchain also "fixes" this. IIRC Neovide doesn't have a specified minimal supported rust version, so we *can* expect users who compile it to use the latest version, but it's a minor readability thing (which already has caused some confusions such as this one), so we can use the older way.
But right now it wouldn't be the same, because you omitted the formatting argument, it should be `{:.1}ms` (in all three lines).
If you fix that, we can merge this to avoid further confusion for such minor thing.

**Comment by huncut2016** [comment]
@LoipesMas I'm done!

**Comment by LoipesMas** [comment]
Thanks!

**Pull request merged**
