### PR TITLE
Fix snap package depdencencies

### LINKED ISSUE #870: Permission denied on Linux
**Describe the bug**
Just like (#831) when I tried to run snap version of neovide, it panicked at Result::Err. When I ran `neovide --log` it gave output:
```sh
-> neovide --log
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: GlobError { path: ".", error: Os { code: 13, kind: PermissionDenied, message: "Permission denied" } }', /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:150:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/flexi_logger-0.17.1/src/writers/file_log_writer.rs:73:57

```
So I noticed Permission denied error and I tried to run as administrator with `sudo` and
```sh
-> sudo neovide --log
mkdir: cannot create directory ‘/run/user/0’: Permission denied
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: GlobError { path: ".", error: Os { code: 13, kind: PermissionDenied, message: "Permission denied" } }', /rustc/53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b/library/core/src/ops/function.rs:150:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: PoisonError { .. }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/flexi_logger-0.17.1/src/writers/file_log_writer.rs:73:57
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Neovide Version latest 
 - Neovim Version latest

### PR DESCRIPTION
**Pull request by leon332157**
## What kind of change does this PR introduce?
- Fixes #870 and #831

## Did this PR introduce a breaking change? 
_A breaking change includes anything that breaks backwards compatibility either at compile or run time._
- No

### Changes introduced:
- switch base snap to Ubuntu 20.04
- Included libxfbcommon and libegl/libgl

I was able to build and install the snap locally with --devmode, However, I wasn't able to install with strict confimenent, since snap can't verify local packages. Maybe we should push to "edge" channel first to test it on other machines.

### CODE REVIEW

**Comment by Kethku** [comment]
@j4qfrost

**Comment by j4qfrost** [comment]
Sorry I was flying, I'll take a look in a bit.

**Comment by leon332157** [comment]
any updates on this?

**Comment by Kethku** [comment]
This seems reasonable to me. I just know very little about the snap package infrastructure so I will differ to others who know more

**Comment by j4qfrost** [comment]
I will spin up an Ubuntu VM to publish this to edge and then to stable.
Sorry there were issues with my flight and I didn't get the chance to push
this out to snap yet.

**Comment by leon332157** [comment]
no worries, no rush, just wanted to make sure this is still active.

**Comment by leon332157** [comment]
@j4qfrost

**Comment by j4qfrost** [comment]
On it.

**Comment by j4qfrost** [comment]
Once you merge in these changes, I think the PR is ready to be accepted. https://github.com/leon332157/neovide/pull/1

**Comment by leon332157** [comment]
should I merge to master instead?

**Comment by j4qfrost** [comment]
@leon332157 Yes, I actually don't think some builds will trigger without merging to master.

**Comment by j4qfrost** [comment]
Oh shoot, make sure my changes get merged into your branch first.

**Comment by leon332157** [comment]
ready now 👌

**Pull request merged**
